#API version and kind
apiVersion: apps/v1
kind: Deployment

#Metadata

metadata:
  name: ml-experiment-logger

#Spec
spec:
  replicas : 1
  selector:
    matchLabels:
      app: ml-experiment-logger
  template:
    metadata:
      labels:
        app: ml-experiment-logger
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: ml-experiment-logger
          image: ml-experiment-logger:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: experiment-storage
              mountPath: /app/data
      volumes:
        - name: experiment-storage
          persistentVolumeClaim:
            claimName: ml-experiment-pvc
