name: Build Docker Image

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Build Docker Image
        run: docker build -t my-mlops-img ./ML_Experiment_Logger